version: '3.8'

services:

  enrichment_exporter:
    image: ghcr.io/krinkuto11/enrichment_exporter:latest
    container_name: enrichment_exporter
    ports:
      - "9101:9101"
    environment:
      - CHANNEL_LOOKUP_URL=${ACESTREAM_SCRAPER_URL}/api/tv-channels/find-matches
      - PGID=1000
      - PUID=1000
      - ACEXY_API=http://localhost:8080/ace/status
